# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # setup node env     
    - name: setup Node.js enviroment
      uses: actions/setup-node@v2-beta
      with:
        version: 12
    # setup yarn for git
    -name: github action for yarn
     uses: borales/actions-yarn@v2.1.0
     with:
      cmd: install
    # creating build      
    -name: creating build
     run: yarn build
    # installing surge      
    - name: installing surge
      run: npm install -g surge
    # deloying app with surge
    - name: deploying on surge
      run: surge ./build http://react.session.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
